"""
Export a curated wireframe line list from the Ohio submarine Blender model.

The article hero (src/components/NeutrinoSubmarineHero.tsx) draws the
submarine as thin lines. Drawing every mesh edge would be a hairball, so this
picks the edges that read as an engineering drawing: sparse rings and
longitudinals on the hull, feature edges on the sail and missile deck, and
outlines for the control surfaces and propeller. Tiny fittings (draft ticks,
hinges, seals) are skipped.

Usage (from the repo root):

    blender --factory-startup -b ~/art/submarine_3dmodel/Ohio_Submarine.blend \
        --python scripts/export_sub_wire.py -- src/assets/neutrino_submarines/sub_wire

Writes <prefix>.bin (little-endian int16, six per segment: x0 y0 z0 x1 y1 z1,
quantized to the bounding box) and <prefix>.json (segment count, bounds, and
the unquantize formula). Meshes are read before modifiers so bevels do not
spray extra edges. Coordinates are metres; the sub points along +X, Z is up.
"""
import bpy, struct, json, sys, math
from collections import defaultdict

OUT = sys.argv[sys.argv.index('--') + 1]
FEATURE_DEG = 30.0

KEEP_PREFIX = (
    'Pressure hull', 'Raised missile deck', 'Missile hatch', 'Sail •', 'Sail crown',
    'Retractable mast', 'Mast head', 'Sail diving plane', 'Stern horizontal', 'Stern vertical',
    'Propeller shaft', 'Propeller hub', 'Skewed propeller blade', 'Deck access hatch',
    'Bridge access hatch', 'Optical head', 'Radar',
)
SKIP_SUBSTR = ('seal',)  # hatch seals duplicate the lids

segs = []


def add(a, b):
    segs.append((*a, *b))


def feature_edges(o, thresh_deg=FEATURE_DEG):
    """Boundary edges plus edges whose two faces meet at more than thresh_deg."""
    me, M = o.data, o.matrix_world
    adj = defaultdict(list)
    for p in me.polygons:
        for ek in p.edge_keys:
            adj[ek].append(p.normal)
    cos_t = math.cos(math.radians(thresh_deg))
    for e in me.edges:
        k = tuple(sorted(e.vertices))
        ns = adj.get(k, [])
        if len(ns) < 2 or ns[0].dot(ns[1]) < cos_t:
            add(M @ me.vertices[k[0]].co, M @ me.vertices[k[1]].co)


def ring_index(o, axis):
    """Group vertices into rings of constant coordinate along `axis` (0=x, 2=z),
    each sorted by angle about that axis. Works for any lathe-like primitive
    regardless of Blender's vertex ordering."""
    me = o.data
    other = [i for i in range(3) if i != axis]
    groups = defaultdict(list)
    for v in me.vertices:
        groups[round(v.co[axis], 4)].append(v)
    rings = []
    for key in sorted(groups):
        vs = groups[key]
        vs.sort(key=lambda v: math.atan2(v.co[other[1]], v.co[other[0]]))
        rings.append(vs)
    return rings


def lathe_outline(o, axis, ring_stride, longitudinals, ring_step=1, min_ring_size=3):
    """Every ring_stride-th ring plus `longitudinals` evenly spaced meridians.
    `axis` is the object's *local* lathe axis (Blender primitives are built
    around local Z; the object's rotation is applied afterwards by
    matrix_world). `ring_step` skips vertices around each ring so a 48-gon
    can be drawn as a 12-gon."""
    M = o.matrix_world
    rings = [r for r in ring_index(o, axis) if len(r) >= min_ring_size]
    if not rings:
        return
    for i in range(0, len(rings), ring_stride):
        r = rings[i]
        n = len(r)
        for k in range(0, n, ring_step):
            add(M @ r[k].co, M @ r[(k + ring_step) % n].co)
    if len(rings) > 1 and longitudinals:
        n = len(rings[0])
        for k in range(0, n, max(1, n // longitudinals)):
            for i in range(len(rings) - 1):
                a, b = rings[i], rings[i + 1]
                if len(a) == n and len(b) == n:
                    add(M @ a[k].co, M @ b[k].co)


def ellipsoid_outline(center, semi_axes, rings=5, meridians=4, n=24):
    """Analytic rings perpendicular to X plus meridians, for the propeller hub.
    (The hub mesh is a UV sphere with poles on Z, so its own topology gives
    rings in the wrong plane.)"""
    cx, cy, cz = center
    ax, ay, az = semi_axes
    for i in range(1, rings + 1):
        u = -1 + 2 * i / (rings + 1)          # (-1, 1), skip the poles
        x = cx + ax * u
        rr = math.sqrt(max(0.0, 1 - u * u))
        pts = [(x, cy + ay * rr * math.cos(2 * math.pi * k / n), cz + az * rr * math.sin(2 * math.pi * k / n)) for k in range(n)]
        for k in range(n):
            add(pts[k], pts[(k + 1) % n])
    for j in range(meridians):
        t = 2 * math.pi * j / meridians
        pts = [(cx + ax * math.cos(a), cy + ay * math.sin(a) * math.cos(t), cz + az * math.sin(a) * math.sin(t)) for a in [math.pi * k / n for k in range(n + 1)]]
        for k in range(n):
            add(pts[k], pts[k + 1])


def sampled_lathe(o, n, ring_stride, long_stride):
    """Hull: vertex index = ring*n + k, generated by create_submarine.py."""
    me, M = o.data, o.matrix_world
    nrings = len(me.vertices) // n
    for i in range(0, nrings, ring_stride):
        for k in range(n):
            add(M @ me.vertices[i * n + k].co, M @ me.vertices[i * n + (k + 1) % n].co)
    for k in range(0, n, long_stride):
        for i in range(nrings - 1):
            add(M @ me.vertices[i * n + k].co, M @ me.vertices[(i + 1) * n + k].co)


def loft_outline(o, ring_size, n_rings, rings_to_draw, chords):
    """Foils and propeller blades: `n_rings` rings of `ring_size` verts."""
    me, M = o.data, o.matrix_world
    for ring in rings_to_draw:
        for k in range(ring_size):
            add(M @ me.vertices[ring * ring_size + k].co,
                M @ me.vertices[ring * ring_size + (k + 1) % ring_size].co)
    for k in chords:
        for r in range(n_rings - 1):
            add(M @ me.vertices[r * ring_size + k].co, M @ me.vertices[(r + 1) * ring_size + k].co)


for o in bpy.data.objects:
    if o.type != 'MESH' or not o.name.startswith(KEEP_PREFIX):
        continue
    if any(s in o.name for s in SKIP_SUBSTR):
        continue
    name = o.name
    if name.startswith('Pressure hull'):
        sampled_lathe(o, 128, ring_stride=8, long_stride=16)
    elif name.startswith('Propeller hub'):
        # UV sphere, radius 1, scaled by the object: draw it analytically.
        ellipsoid_outline(o.matrix_world.translation, o.scale, rings=4, meridians=4)
    elif name.startswith('Propeller shaft'):
        # Z cylinder rotated onto X by the object transform: group along local Z.
        lathe_outline(o, axis=2, ring_stride=1, longitudinals=4, ring_step=4)
    elif name.startswith(('Retractable mast', 'Mast head')):
        lathe_outline(o, axis=2, ring_stride=1, longitudinals=4, ring_step=4)
    elif name.startswith('Sail • streamlined fairwater'):
        feature_edges(o)
        me, M = o.data, o.matrix_world
        half = len(me.vertices) // 2
        for i in range(0, half, 2):
            add(M @ me.vertices[i].co, M @ me.vertices[i + half].co)
    elif name.startswith(('Sail diving', 'Stern ')):
        loft_outline(o, 24, 5, rings_to_draw=(0, 4), chords=(0, 6, 12, 18))
    elif name.startswith('Skewed propeller'):
        loft_outline(o, 20, 5, rings_to_draw=(0, 4), chords=(0, 10))
    else:
        feature_edges(o)

# Quantize to int16 over the bounding box.
lo = [min(min(s[i], s[i + 3]) for s in segs) for i in range(3)]
hi = [max(max(s[i], s[i + 3]) for s in segs) for i in range(3)]
scale = [(h - l) or 1.0 for l, h in zip(lo, hi)]


def q(v, i):
    return int(round((v - lo[i]) / scale[i] * 65535)) - 32768


buf = bytearray()
for s in segs:
    buf += struct.pack('<6h', *(q(s[i], i % 3) for i in range(6)))
with open(OUT + '.bin', 'wb') as f:
    f.write(buf)
with open(OUT + '.json', 'w') as f:
    json.dump({
        'segments': len(segs),
        'min': [round(v, 4) for v in lo],
        'max': [round(v, 4) for v in hi],
        'format': 'little-endian int16, 6 per segment (x0 y0 z0 x1 y1 z1); v = min + (q + 32768) / 65535 * (max - min)',
        'units': 'metres, +X bow, +Z up',
    }, f, indent=2)
print('SEGMENTS', len(segs), 'BYTES', len(buf))
